name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: jyothikacodes

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Generate Pacman contribution graph'